### ISSUE TITLE
Gérer les droits d'accés de l'Explorateur

### ISSUE THREAD

**Issue by b4-b4** [b4-b4/wct#6]
### Les Modifications Suivantes Ne Devront Être Apporté qu'À Partir Du Moment Où l'Explorateur De Dossiers Fonctionnera
---
Si vous utilisez la commande `smwct` spécifiant que vous voulez fouillez au niveau `/` (root), vous vous apercevrez qu'une erreur vous informe que vous n'avez pas le droit d'entrer dans X dossier. Ce problème peut être résout de manière différente :

- Soit on part celle-ci avec `try` + `catch` en passant outre le répertoire privée ;
- Soit, par un moyen X ou Y,  on fait en sorte de sois débloquer l'accés au répertoire en question, sois un autre moyen qui y serai semblable.

**Comment by antoineB24** [comment]
alors juste pour te dire que ce probleme **n'est plus notre probleme**. elle peut etre tres bien gere par l'OS : 
 - Sur Linux/MacOS un sudo wct suffira
 - sur Windows, le mode root suffira

**Comment by b4-b4** [comment]
Génial. C'est vrai que je n'ai jamais lancé une commande python avec `sudo`.

**Comment by antoineB24** [comment]
alors je ne suis pas sur que ca va comme meme marche test sur linux si tu peux
